export default interface Account {
    id?: number,
    account: string,
    firstName: string,
    lastName: string,
    password: string,
    email: string,
    phone: string,
    nationality: string,
    address: string,
    birthday: string,
    memberType: string,
    memberLevel: string,
    memberPoints: number,
    memberStatus: string,
    lastLoginLime: string,
    sessionToken: string,
    isPhoneVerified: boolean,
}
