export default interface CouponType {
    id?: number,
    categoryIds?: string[],
    name?: string,
    code?: string,
    isLimited?: boolean,
    discountType?: number,
    discountPercentage?: number,
    availableArea?: string[],
    availableAmount?: number,
    restriction?: string[],
    startTime?: string,
    endTime?: string,
    imageUrl?: string,
    isEnabled?: boolean,
}